# Generated by Django 5.1.7 on 2025-12-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('status', models.CharField(choices=[('NEW', 'New Applied'), ('SCREENED', 'AI Screened'), ('INTERVIEW', 'Interview Scheduled'), ('OFFER', 'Offer Sent'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('ai_match_score', models.IntegerField(blank=True, help_text='0-100 score from Gemini', null=True)),
                ('ai_summary', models.TextField(blank=True, help_text='AI generated summary of the candidate')),
                ('ai_missing_skills', models.JSONField(blank=True, default=list, help_text='Skills from JD missing in resume')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobposting')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate')),
            ],
        ),
    ]
