# Generated by Django 5.2.9 on 2025-12-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='answers',
            field=models.JSONField(blank=True, default=list, help_text='Candidate answers to screening questions'),
        ),
    ]
