# Generated by Django 5.1.2 on 2025-12-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_application_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='platform',
            field=models.CharField(blank=True, default='Website', max_length=50),
        ),
    ]
