# Generated by Django 5.2.9 on 2025-12-12 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_application_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='experience_years',
            field=models.IntegerField(blank=True, help_text='Years of professional experience', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='platform',
            field=models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('INDEED', 'Indeed'), ('GLASSDOOR', 'Glassdoor'), ('NAUKRI', 'Naukri'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='candidates.application')),
            ],
        ),
    ]
