# Generated by Django 5.2.9 on 2025-12-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_application_experience_years_application_platform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='linkedin_url',
        ),
    ]
