# Generated by Django 5.2.9 on 2025-12-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_remove_candidate_linkedin_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='ai_match_score',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ai_missing_skills',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ai_summary',
        ),
    ]
