# Generated by Django 5.2.9 on 2025-12-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_remove_application_ai_match_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='current_ctc',
            field=models.CharField(blank=True, help_text='Current CTC (e.g. 12 LPA)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='expected_ctc',
            field=models.CharField(blank=True, help_text='Expected CTC', max_length=50, null=True),
        ),
    ]
