# Generated by Django 5.2.9 on 2025-12-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_application_current_ctc_application_expected_ctc'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notice_period',
            field=models.IntegerField(blank=True, help_text='Notice period in days', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='current_ctc',
            field=models.FloatField(blank=True, help_text='Current CTC in Lakhs (e.g. 11.5)', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='expected_ctc',
            field=models.FloatField(blank=True, help_text='Expected CTC in Lakhs', null=True),
        ),
    ]
