# Generated by Django 5.2.9 on 2025-12-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_application_notice_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='previous_experience',
            field=models.TextField(blank=True, help_text='Previous companies and roles (JSON/Text)'),
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills'),
        ),
    ]
