# Generated by Django 5.1.2 on 2025-12-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_application_platform'),
        ('candidates', '0007_application_notice_period_and_more'),
    ]

    operations = [
    ]
