# Generated by Django 5.2.9 on 2025-12-15 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_application_previous_experience_application_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='previous_experience',
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('duration', models.CharField(blank=True, help_text='e.g. 2 years, 2020-2022', max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidates.application')),
            ],
        ),
    ]
