# Generated by Django 5.1.2 on 2025-12-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_merge_20251213_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='platform',
            field=models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('INDEED', 'Indeed'), ('GLASSDOOR', 'Glassdoor'), ('NAUKRI', 'Naukri'), ('CUSTOM', 'Custom'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
