# Generated by Django 5.2.9 on 2025-12-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_alter_application_platform'),
        ('candidates', '0009_remove_application_previous_experience_experience'),
    ]

    operations = [
    ]
