# Generated by Django 5.2.9 on 2025-12-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_merge_20251215_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='platform',
            field=models.CharField(default='Website', help_text='Source platform (e.g. LinkedIn, Indeed, Custom)', max_length=50),
        ),
    ]
