# Generated by Django 5.2.9 on 2025-12-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_application_certifications_application_education_and_more'),
        ('candidates', '0011_alter_application_platform'),
    ]

    operations = [
    ]
