# Generated by Django 5.2.9 on 2025-12-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_merge_20251217_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='skills',
        ),
    ]
