# Generated by Django 5.2.9 on 2025-12-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_remove_application_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills'),
        ),
    ]
