# Generated by Django 5.1.4 on 2025-12-17 09:53

from django.db import migrations, models
import json


def convert_skills_to_json(apps, schema_editor):
    """Convert TextField skills to JSONField-compatible format."""
    Application = apps.get_model('candidates', 'Application')
    for app in Application.objects.all():
        current_skills = app.skills
        if current_skills is None or current_skills == '':
            # Empty string -> empty list
            app.skills = '[]'
        elif isinstance(current_skills, str):
            # Try to parse as JSON first
            try:
                json.loads(current_skills)
                # Already valid JSON, keep as-is
            except json.JSONDecodeError:
                # Comma-separated string -> JSON array
                skills_list = [s.strip() for s in current_skills.split(',') if s.strip()]
                app.skills = json.dumps(skills_list)
        app.save(update_fields=['skills'])


def reverse_skills_to_text(apps, schema_editor):
    """Convert JSONField skills back to TextField format."""
    Application = apps.get_model('candidates', 'Application')
    for app in Application.objects.all():
        if app.skills:
            try:
                skills_list = json.loads(app.skills) if isinstance(app.skills, str) else app.skills
                app.skills = ', '.join(skills_list) if skills_list else ''
            except (json.JSONDecodeError, TypeError):
                app.skills = ''
        else:
            app.skills = ''
        app.save(update_fields=['skills'])


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_application_skills'),
    ]

    operations = [
        # First, convert existing text data to valid JSON strings
        migrations.RunPython(convert_skills_to_json, reverse_skills_to_text),
        # Then alter the field type
        migrations.AlterField(
            model_name='application',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skills'),
        ),
    ]
