# Generated by Django 5.1.4 on 2025-12-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_application_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skills'),
        ),
    ]
