# Generated by Django 5.1.4 on 2026-01-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_alter_application_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Internal notes for recruiters'),
        ),
    ]
