# Generated by Django 5.1.4 on 2026-01-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_application_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Applied'), ('SCREENED', 'AI Screened'), ('INTERVIEW', 'Interview Scheduled'), ('OFFER', 'Offer Sent'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='NEW', max_length=20),
        ),
    ]
