# Generated by Django 5.1.4 on 2026-01-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0018_application_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rejected_stage',
            field=models.CharField(blank=True, help_text='The stage at which the candidate was rejected', max_length=20, null=True),
        ),
    ]
