# Generated by Django 5.1.2 on 2025-12-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscreenai', '0002_employee_first_name_employee_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
