# Generated by Django 5.1.2 on 2025-12-12 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscreenai', '0003_application_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='appscreenai.employee'),
        ),
        migrations.AlterField(
            model_name='application',
            name='job_id',
            field=models.IntegerField(blank=True, help_text='ID of the job this application belongs to', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='source',
            field=models.CharField(blank=True, help_text='LinkedIn, Indeed, Website, Naukri etc', max_length=50),
        ),
    ]
