# Generated by Django 5.1.7 on 2025-12-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Full job description')),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ONSITE', 'On-site')], default='ONSITE', max_length=20)),
                ('required_skills', models.JSONField(default=list, help_text='List of mandatory skills for AI matching')),
                ('screening_questions', models.JSONField(blank=True, default=list, help_text='Custom questions for the candidate')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
