# Generated by Django 5.2.9 on 2025-12-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='department',
            field=models.CharField(default='Engineering', max_length=100),
        ),
    ]
