# Generated by Django 5.2.9 on 2025-12-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobposting_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='salary_range',
            field=models.CharField(blank=True, help_text='e.g. 12-15 LPA', max_length=100, null=True),
        ),
    ]
