# Generated by Django 5.2.9 on 2025-12-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobposting_salary_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='expected_ctc_limit',
            field=models.FloatField(default=20.0, help_text='Max Expected CTC considered (Slider value)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='min_experience',
            field=models.IntegerField(default=1, help_text='Minimum Years of Experience'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='notice_period_days',
            field=models.IntegerField(default=30, help_text='Max acceptable notice period in days'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='offered_ctc',
            field=models.FloatField(default=12.0, help_text='Target Offered CTC in Lakhs (Slider value)'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='salary_range',
            field=models.CharField(blank=True, help_text='Text description e.g. 12-15 LPA', max_length=100, null=True),
        ),
    ]
