# Generated by Django 5.2.9 on 2025-12-12 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscreenai', '0001_initial'),
        ('jobs', '0004_jobposting_expected_ctc_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='appscreenai.employee'),
        ),
    ]
