# Generated by Django 5.2.9 on 2025-12-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobposting_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='target_companies',
            field=models.JSONField(blank=True, default=list, help_text='List of target companies'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='target_roles',
            field=models.JSONField(blank=True, default=list, help_text='List of target job roles'),
        ),
    ]
