# Generated by Django 5.2.9 on 2025-12-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobposting_target_companies_jobposting_target_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='target_companies',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='target_roles',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='previous_companies',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred previous companies'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='previous_roles',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred previous job roles'),
        ),
    ]
