# Generated by Django 5.2.9 on 2025-12-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_jobposting_target_companies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='custom_platforms',
            field=models.JSONField(blank=True, default=list, help_text='List of custom platform names'),
        ),
    ]
