# Generated by Django 5.1.4 on 2026-01-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobposting_custom_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Internal notes for recruiters'),
        ),
    ]
