# Generated by Django 6.0 on 2026-01-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobposting_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='interview_rounds',
            field=models.IntegerField(default=3, help_text='Number of interview rounds for this job'),
        ),
    ]
